name: Check URL links

on: [push, pull_request]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Check URL links
        uses: paramt/url-checker@master
        with:
          files: "README.md"
